/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jahid
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnPoint = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnKaliza = new javax.swing.JButton();
        jbtnMojo = new javax.swing.JButton();
        jbtnChickenBriyani = new javax.swing.JButton();
        jbtnSprite = new javax.swing.JButton();
        jbtnFriedRice = new javax.swing.JButton();
        jbtnSingara = new javax.swing.JButton();
        jbtnVhortaVhaji = new javax.swing.JButton();
        jbtnRicePackage = new javax.swing.JButton();
        jbtnTea = new javax.swing.JButton();
        jbtnBeefKacchi = new javax.swing.JButton();
        jbtnCocacola = new javax.swing.JButton();
        jbtnSamusa = new javax.swing.JButton();
        jbtnFriedFish = new javax.swing.JButton();
        jbtnCoffee = new javax.swing.JButton();
        jbtnChicken = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcboPayment = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jtxtBarCode = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 70));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 70));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 70));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 70));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, 70));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, 70));

        jbtnPoint.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPoint.setText(".");
        jbtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPointActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, 70));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 70));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, 70));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 70));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, 70));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 80, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 140, 280, 350));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnKaliza.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnKaliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/singara.jpeg"))); // NOI18N
        jbtnKaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKalizaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnKaliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 100));

        jbtnMojo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mojo.jpg"))); // NOI18N
        jbtnMojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMojoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 100));

        jbtnChickenBriyani.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnChickenBriyani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chichen kacchi.jpg"))); // NOI18N
        jbtnChickenBriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenBriyaniActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnChickenBriyani, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 100));

        jbtnSprite.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Sprite.jpg"))); // NOI18N
        jbtnSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSpriteActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 100));

        jbtnFriedRice.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnFriedRice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fried rice.jpg"))); // NOI18N
        jbtnFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFriedRiceActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnFriedRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 120, 100));

        jbtnSingara.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSingara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kolijar-singara.jpg"))); // NOI18N
        jbtnSingara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSingaraActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSingara, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 120, 100));

        jbtnVhortaVhaji.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnVhortaVhaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vhorta-vhaji.jpeg"))); // NOI18N
        jbtnVhortaVhaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVhortaVhajiActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnVhortaVhaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 120, 100));

        jbtnRicePackage.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnRicePackage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rice and Dal.jpg"))); // NOI18N
        jbtnRicePackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRicePackageActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnRicePackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 120, 100));

        jbtnTea.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnTea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tea.jpg"))); // NOI18N
        jbtnTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTeaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 120, 100));

        jbtnBeefKacchi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnBeefKacchi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/beef kacchi.jpg"))); // NOI18N
        jbtnBeefKacchi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBeefKacchiActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBeefKacchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 120, 100));

        jbtnCocacola.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCocacola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cocacola.jpg"))); // NOI18N
        jbtnCocacola.setMargin(new java.awt.Insets(2, 2, 3, 14));
        jbtnCocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCocacolaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCocacola, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 100));

        jbtnSamusa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSamusa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Samusa.jpeg"))); // NOI18N
        jbtnSamusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSamusaActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSamusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, 100));

        jbtnFriedFish.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnFriedFish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Fried Fish.jpg"))); // NOI18N
        jbtnFriedFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFriedFishActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnFriedFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 120, 100));

        jbtnCoffee.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/coffee.jpg"))); // NOI18N
        jbtnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoffeeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 120, 100));

        jbtnChicken.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnChicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chicken.jpg"))); // NOI18N
        jbtnChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnChicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 120, 100));

        jLabel7.setText("Tea");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 50, 20));

        jLabel8.setText("Rice Package");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 90, -1));

        jLabel9.setText("Chicken Briyani ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, -1));

        jLabel10.setText("Beef Kacchi ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 110, -1));

        jLabel11.setText("Sprite 250 ml");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 70, -1));

        jLabel12.setText("Mojo 250 ml");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        jLabel13.setText("Cocacola 250 ml");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 90, -1));

        jLabel14.setText("Singara");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 60, -1));

        jLabel15.setText("Samusa");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 50, -1));

        jLabel16.setText("Vhorta Vhaji");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 90, -1));

        jLabel17.setText("Jhal Chichen ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 90, -1));

        jLabel18.setText("Fried Fish");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 90, -1));

        jLabel19.setText("Kaliza Singara");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, -1));

        jLabel21.setText("Fried Rice");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 90, -1));

        jLabel20.setText("Coffee");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 720, 440));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 350, 440));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Subtotal");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Tax");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, 40));

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel5.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 180, 40));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel5.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 390, 170));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 200, 40));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel6.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 200, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Cash");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Payment Method");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Change");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 40));

        jcboPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Bkash", "Nagad", "Visa Card" }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel6.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 170, 40));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 450, 170));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, 40));

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 40));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 180, 40));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 40));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 40));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 330, 170));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 1350, 190));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DhTt", 0, 48)); // NOI18N
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 510, 250, 60));

        jLabel22.setBackground(new java.awt.Color(204, 255, 153));
        jLabel22.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Food Orderring System");
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 80));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText(" Input Amount of Cash");
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, 280, 40));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("           Display Item List");
        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 350, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setText("                               Select Item to purchase");
        jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 720, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    
    
    
    
    public void ItemCost()
    {
        double sum = 0;
        for (int i = 0; i<jTable1.getRowCount();i++){
            sum = sum +  Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 * 5)/100;
        String  iTaxTotal = String.format(" $ %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String  iSubTotal = String.format(" $ %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
        String  iTotal = String.format(" $ %.2f", cTotal1 + cTax);
        jtxtTotal.setText(iTotal);
         
        String  BarCode = String.format(" Total is %.2f", cTotal1 + cTax);
        jtxtBarCode.setText(BarCode);
        
        
    }
    
    
    
    
    public void Change(){
        double sum = 0;
        double tax = 5;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        
        for( int i = 0; i<jTable1.getRowCount(); i++){
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        double cTax = (sum *5)/100;
        double cChange = (cash - (sum +cTax));
        
        
        String ChangeGiven = String.format("$ %.2f", cChange);
        jtxtChange.setText(ChangeGiven);
        
        
        
        
    }
    
    
    
    
    
    
    
    
    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn9.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn9.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn7.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn7.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn8.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn8.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn4.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn4.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn5.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn5.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn6.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn6.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPointActionPerformed
        
        if(! jtxtDisplay.getText().contains(".")){
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtnPoint.getText());
        }
    }//GEN-LAST:event_jbtnPointActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn0.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn0.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText(""); 
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn1.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn1.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn2.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn2.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jbtn3.getText());
        }
        else{
            EnterNumber = jtxtDisplay.getText() + jbtn3.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnKalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKalizaActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 15;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Kaliza Singara", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnKalizaActionPerformed

    private void jbtnMojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMojoActionPerformed
        double PriceOfItem = 25;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"MOJO 250 ml", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnMojoActionPerformed

    private void jbtnChickenBriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenBriyaniActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 150;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chicken Briyani", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnChickenBriyaniActionPerformed

    private void jbtnSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSpriteActionPerformed
        
        double PriceOfItem = 25;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sprite 250ml", "1", PriceOfItem});
        ItemCost();
        
    }//GEN-LAST:event_jbtnSpriteActionPerformed

    private void jbtnFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFriedRiceActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 100;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Fried Rice", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnFriedRiceActionPerformed

    private void jbtnSingaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSingaraActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 10;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Singara Regular", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSingaraActionPerformed

    private void jbtnVhortaVhajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVhortaVhajiActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 30;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Vhorta Vhaji", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnVhortaVhajiActionPerformed

    private void jbtnRicePackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRicePackageActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 80;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rice Package", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRicePackageActionPerformed

    private void jbtnTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTeaActionPerformed
        double PriceOfItem = 8;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Tea", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnTeaActionPerformed

    private void jbtnBeefKacchiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBeefKacchiActionPerformed
        double PriceOfItem = 160;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Beef Kacchi", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnBeefKacchiActionPerformed

    private void jbtnCocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCocacolaActionPerformed
        double PriceOfItem = 35;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"CocaCola 250ml", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnCocacolaActionPerformed

    private void jbtnSamusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSamusaActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 10;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Samusa", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSamusaActionPerformed

    private void jbtnFriedFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFriedFishActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 60;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Fried Fish", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnFriedFishActionPerformed

    private void jbtnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoffeeActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 15;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coffee", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnCoffeeActionPerformed

    private void jbtnChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 80;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Jhal Chicken", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnChickenActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Food Ordering System.",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        // TODO add your handling code here:
        if(jcboPayment.getSelectedItem().equals("Cash")){
            Change();
        }else{
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
       
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page (0, number, integer)");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
            
        }catch(PrinterException e){
            System.err.format("No Printer FOund", e.getMessage());
        }
        
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int RemoveItem = jTable1.getSelectedRow();
        if(RemoveItem >=0 ){
            model.removeRow(RemoveItem);
        }
        ItemCost();
        
        if(jcboPayment.getSelectedItem().equals("Cash")){
            Change();
        }else{
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBeefKacchi;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnChicken;
    private javax.swing.JButton jbtnChickenBriyani;
    private javax.swing.JButton jbtnCocacola;
    private javax.swing.JButton jbtnCoffee;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnFriedFish;
    private javax.swing.JButton jbtnFriedRice;
    private javax.swing.JButton jbtnKaliza;
    private javax.swing.JButton jbtnMojo;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPoint;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnRicePackage;
    private javax.swing.JButton jbtnSamusa;
    private javax.swing.JButton jbtnSingara;
    private javax.swing.JButton jbtnSprite;
    private javax.swing.JButton jbtnTea;
    private javax.swing.JButton jbtnVhortaVhaji;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
